# Generated by Django 5.1.1 on 2024-09-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("color", models.CharField(blank=True, max_length=100, null=True)),
                ("capacity", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("generation", models.CharField(blank=True, max_length=50, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("cpu_model", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "hard_disk_size",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "strap_color",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("case_size", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
